### PR TITLE
Fix release version info validation workflow

### LINKED ISSUE #98: Fix validate release info workflow
- The workflow runs the job and fails even when documentation tags exist on a PR
- The job should only run when there IS a release tag or there IS NOT a documentation tag
- The issue may be related to the weird handling of env variables and outputs

### PR DESCRIPTION
**Pull request by PatrickDeVries**
### Why:

Closes #98 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

- Add `${{}}` around env variables to evaluate the expressions immediately instead of storing strings
- Move `if` to individual steps to allow accessing env vars without needing an extra job

### CODE REVIEW

File: packages/too-many-hooks/src/useArray.ts [hunk 1]
```diff
@@ -23,6 +23,7 @@ export type UseArrayReturn<T> = [
      *
      * @type {() => void}
      */
+
```
Comment (dawsonbooth) [inline packages/too-many-hooks/src/useArray.ts:26]: What's this for?

**Review by dawsonbooth — APPROVED** [review]
